-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE
     , REST_ID
     , REST_NAME
     , FAVORITES
  FROM REST_INFO
     , (SELECT FOOD_TYPE
             , MAX(FAVORITES) AS FAV
          FROM REST_INFO
         GROUP BY FOOD_TYPE
     ) FAV_INFO
 WHERE 1 = 1
   AND FAV_INFO.FAV = FAVORITES
   AND REST_INFO.FOOD_TYPE = FAV_INFO.FOOD_TYPE
 ORDER BY FOOD_TYPE DESC