-- 코드를 입력하세요
SELECT A.CAR_ID
     , A.CAR_TYPE 
     , A.DAILY_FEE * (100 - C.DISCOUNT_RATE) * 30 / 100 AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
     , CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
 WHERE A.CAR_TYPE = C.CAR_TYPE
   AND A.CAR_TYPE IN ('SUV', '세단')
   AND C.DURATION_TYPE = '30일 이상'
   AND A.DAILY_FEE* (100 - C.DISCOUNT_RATE) * 30 / 100 BETWEEN 500000 AND 2000000 
   AND NOT EXISTS
                (
                    SELECT 1
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                    WHERE TO_CHAR(B.START_DATE , 'YYYYMMDD') <= '20221130'
                      AND TO_CHAR(B.END_DATE , 'YYYYMMDD') >= '20221101'
                      AND A.CAR_ID = B.CAR_ID
                )
ORDER BY A.DAILY_FEE* 30 DESC, A.CAR_TYPE ASC, A.CAR_ID DESC
