-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID
     , ANIMAL_OUTS.ANIMAL_TYPE
     , ANIMAL_OUTS.NAME
  FROM (
           SELECT ANIMAL_ID
                , SEX_UPON_INTAKE
             FROM ANIMAL_INS
            WHERE SEX_UPON_INTAKE LIKE 'Intact%'
       ) INS
       , ANIMAL_OUTS
 WHERE 1 = 1
   AND ANIMAL_OUTS.ANIMAL_ID= INS.ANIMAL_ID
   AND (ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%'
         OR ANIMAL_OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%'
        )
ORDER BY ANIMAL_ID, ANIMAL_TYPE, NAME