-- 코드를 입력하세요
WITH CARS AS 
(
SELECT CAR_ID AS C_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
   AND DATE_FORMAT(START_DATE,'%Y%m') BETWEEN '202208' AND '202210'
  GROUP BY CAR_ID
  HAVING COUNT(CAR_ID) >= 5
)
SELECT CAST(DATE_FORMAT(START_DATE, '%m') AS DECIMAL) AS MONTH
     , CAR_ID
     , COUNT(CAR_ID) AS RECORDS 
  FROM CARS
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
   AND CAR_ID = C_ID
   AND DATE_FORMAT(START_DATE, '%Y%m') = '202208'
 GROUP BY CAR_ID
 UNION ALL
SELECT CAST(DATE_FORMAT(START_DATE, '%m') AS DECIMAL) AS MONTH
     , CAR_ID
     , COUNT(CAR_ID) AS RECORDS 
  FROM CARS
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
   AND CAR_ID = C_ID
   AND DATE_FORMAT(START_DATE, '%Y%m') = '202209'
 GROUP BY CAR_ID
 UNION ALL
SELECT CAST(DATE_FORMAT(START_DATE, '%m') AS DECIMAL) AS MONTH
     , CAR_ID
     , COUNT(CAR_ID) AS RECORDS 
  FROM CARS
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
   AND CAR_ID = C_ID
   AND DATE_FORMAT(START_DATE, '%Y%m') = '202210'
 GROUP BY CAR_ID
 ORDER BY MONTH ASC, 
          CAR_ID DESC 
