-- 코드를 입력하세요
SELECT A.USER_ID 
     , A.NICKNAME
     , A.CITY || ' ' || A.STREET_ADDRESS1 || ' ' || A.STREET_ADDRESS2 AS 전체주소
     , SUBSTR(A.TLNO,0,3) || '-' || SUBSTR(A.TLNO,4,4) || '-' || SUBSTR(A.TLNO,8,4) AS 전화번호
  FROM USED_GOODS_USER A
     , USED_GOODS_BOARD B
 WHERE A.USER_ID = B.WRITER_ID
GROUP BY A.USER_ID
     , A.NICKNAME
     , A.CITY || ' ' || A.STREET_ADDRESS1 || ' ' || A.STREET_ADDRESS2
     , SUBSTR(A.TLNO,0,3) || '-' || SUBSTR(A.TLNO,4,4) || '-' || SUBSTR(A.TLNO,8,4)
HAVING COUNT(B.BOARD_ID) >= 3
ORDER BY USER_ID DESC