# -- 코드를 입력하세요
# SELECT DISTINCT A.CAR_ID
#      , B.AVERAGE_DURATION
#   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
#      , (SELECT CAR_ID
#              , ROUND(AVG(DATEDIFF(END_DATE, START_DATE)),1) AS AVERAGE_DURATION    
#           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#          GROUP BY CAR_ID
#         ) B
#  WHERE A.CAR_ID = B.CAR_ID
#    AND B.AVERAGE_DURATION >= 7.0
#  ORDER BY AVERAGE_DURATION DESC , A.CAR_ID DESC
SELECT CAR_ID
     , ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1),1) AS AVERAGE_DURATION    
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE 1 = 1
 GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1),1) >= 7.0
 ORDER BY AVERAGE_DURATION DESC , CAR_ID DESC