-- 코드를 입력하세요
SELECT PRC.CATEGORY
     , PRC.MAX_PRICE 
     , MN.PRODUCT_NAME
  FROM FOOD_PRODUCT MN
     , (SELECT CATEGORY
             , MAX(PRICE) AS MAX_PRICE
          FROM FOOD_PRODUCT 
         WHERE 1 = 1
           AND CATEGORY IN ('과자','국','김치','식용유')
         GROUP BY CATEGORY
     ) PRC
 WHERE 1 = 1
   AND MN.CATEGORY = PRC.CATEGORY
   AND MN.PRICE    = PRC.MAX_PRICE
 GROUP BY CATEGORY
 ORDER BY MAX(PRICE) DESC