-- 코드를 입력하세요
SELECT A.MEMBER_NAME
     , C.REVIEW_TEXT
     , TO_CHAR(C.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM MEMBER_PROFILE A
     , (
         SELECT B.MEMBER_ID 
           FROM (
             SELECT B.MEMBER_ID, COUNT(REVIEW_SCORE)  FROM REST_REVIEW B GROUP BY B.MEMBER_ID ORDER BY  COUNT(REVIEW_SCORE) DESC
            ) B
            WHERE ROWNUM = 1
        ) B
      , REST_REVIEW C
 WHERE 1 = 1
   AND A.MEMBER_ID = B.MEMBER_ID
   AND A.MEMBER_ID = C.MEMBER_ID
ORDER BY TO_CHAR(C.REVIEW_DATE, 'YYYY-MM-DD') ASC, C.REVIEW_TEXT ASC;
   