-- 코드를 입력하세요
SELECT A.AUTHOR_ID
     , C.AUTHOR_NAME
     , A.CATEGORY
     , SUM(A.PRICE * B.SALES) AS SALES
  FROM BOOK A  
 ,  (
SELECT BS.BOOK_ID
     , SUM(BS.SALES) AS SALES
  FROM BOOK_SALES BS
 WHERE TO_CHAR(BS.SALES_DATE, 'YYYYMMDD') BETWEEN '20220101' AND '20220131'
 GROUP BY BS.BOOK_ID 
) B
, AUTHOR C
WHERE A.BOOK_ID = B.BOOK_ID
  AND A.AUTHOR_ID = C.AUTHOR_ID
 GROUP BY A.AUTHOR_ID, C.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC