-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE
     , SUM(OFF.SALES_AMOUNT) * PR.PRICE AS SALES
    
  FROM PRODUCT PR
  JOIN OFFLINE_SALE OFF ON OFF.PRODUCT_ID = PR.PRODUCT_ID
 WHERE 1 = 1
 GROUP BY PR.PRODUCT_ID
 ORDER BY SUM(OFF.SALES_AMOUNT) * PR.PRICE DESC, PR.PRODUCT_CODE ASC