-- 코드를 입력하세요
SELECT A.CAR_ID
,NVL((
        SELECT '대여중'
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
         WHERE TO_CHAR(B.START_DATE, 'YYYYMMDD') <= '20221016'
           AND TO_CHAR(B.END_DATE, 'YYYYMMDD')  >= '20221016'
           AND A.CAR_ID = B.CAR_ID
    ) , '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
GROUP BY A.CAR_ID    
ORDER BY A.CAR_ID DESC