-- 코드를 입력하세요
SELECT A.PRODUCT_ID
     , A.PRODUCT_NAME
     , SUM(B.AMOUNT * A.PRICE) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
     , ( SELECT T.PRODUCT_ID , SUM(T.AMOUNT) AS AMOUNT
           FROM FOOD_ORDER T
          WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMMDD') LIKE '202205%'  
         GROUP BY T.PRODUCT_ID
       ) B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC