-- 코드를 입력하세요
SELECT INF.INGREDIENT_TYPE
     , SUM(HF.TOTAL_ORDER) AS TOTAL_ORDER
  FROM FIRST_HALF HF
  JOIN ICECREAM_INFO INF ON INF.FLAVOR = HF.FLAVOR
 WHERE 1 = 1
 GROUP BY INF.INGREDIENT_TYPE
 ORDER BY SUM(HF.TOTAL_ORDER) ASC
   