-- 코드를 입력하세요
SELECT A.APNT_NO
     , C.PT_NAME
     , A.PT_NO
     , B.MCDP_CD
     , B.DR_NAME
     , A.APNT_YMD
  FROM APPOINTMENT A
     , DOCTOR B
     , PATIENT C
 WHERE A.PT_NO = C.PT_NO
   AND A.MDDR_ID = B.DR_ID
   AND A.APNT_CNCL_YN = 'N'
   AND TO_CHAR(A.APNT_YMD,'YYYYMMDD') = '20220413'
   AND B.MCDP_CD = 'CS'
 ORDER BY APNT_YMD ASC