-- 코드를 작성해주세요
SELECT  A.*
FROM
(
SELECT  SUM(SCORE) AS SCORE
     ,  EMP.EMP_NO
     ,  EMP.EMP_NAME
     ,  EMP.POSITION
     ,  EMP.EMAIL
FROM    HR_DEPARTMENT DEP
   ,    HR_EMPLOYEES  EMP
   ,    HR_GRADE      GRD
WHERE   DEP.DEPT_ID =   EMP.DEPT_ID
AND     EMP.EMP_NO  =   GRD.EMP_NO
AND     GRD.YEAR    =   2022
GROUP   BY  EMP.EMP_NO
     ,  EMP.EMP_NAME
     ,  EMP.POSITION
     ,  EMP.EMAIL
ORDER BY SUM(SCORE) DESC
) A
LIMIT   1